export const DEFAULT_STUDENT_PROFILE = {
  name: "Alex Johnson",
  department: "CSE",
  semester: 6,
  cgpa: 8.5,
  tenth_percentage: 88.0,
  twelfth_percentage: 85.0,
  backlogs: 0,
  known_languages: ["Python", "JavaScript", "Java", "TypeScript"],
  certifications: ["AWS Certified Cloud Practitioner", "Meta Front-End Developer"],
  projects_count: 3,
  internships_count: 1,
  open_source_contributions: 5,
  aptitude_score: 82.0,
  soft_skill_rating: 4.2,
  hackathons_attended: 2,
  leadership_roles: 1,
  target_role: "Full-Stack Developer",
};

export const MOCK_PREDICTION_RESPONSE = {
  placement_probability: 88.5,
  readiness_status: "Ready",
  target_role: "Full-Stack Developer",
  student_name: "Alex Johnson",
  department: "CSE",
  predicted_roles: [
    { role: "Full-Stack Developer", confidence: 42.0 },
    { role: "Data Analyst", confidence: 28.0 },
    { role: "Cloud/DevOps Engineer", confidence: 18.0 },
    { role: "QA Specialist", confidence: 12.0 },
  ],
  shap_factors: [
    {
      feature: "internships_count",
      contribution: 18.5,
      readable_string: "+18.5% due to practical internship experience",
    },
    {
      feature: "cgpa",
      contribution: 12.0,
      readable_string: "+12.0% strong academic CGPA (8.5)",
    },
    {
      feature: "projects_count",
      contribution: 9.2,
      readable_string: "+9.2% robust portfolio with 3 completed projects",
    },
    {
      feature: "aptitude_score",
      contribution: 6.8,
      readable_string: "+6.8% high aptitude assessment score (82%)",
    },
    {
      feature: "certifications",
      contribution: -5.5,
      readable_string: "-5.5% missing advanced cloud/backend certifications",
    },
    {
      feature: "backlogs",
      contribution: 0.0,
      readable_string: "0% backlog penalty (clear academic record)",
    },
  ],
  skill_gap_analysis: {
    target_role: "Full-Stack Developer",
    missing_skills: ["Docker", "Kubernetes", "System Design", "Advanced SQL"],
    acquired_skills: ["React", "JavaScript", "Python", "Git", "REST APIs"],
  },
};

export const MOCK_ROADMAP_RESPONSE = {
  target_role: "Full-Stack Developer",
  total_estimated_weeks: 10,
  phases: [
    {
      phase_number: 1,
      title: "Phase 1: Database & Backend Solidification",
      estimated_weeks: 3,
      progress: 30,
      skills: ["Advanced SQL", "Indexing", "Query Optimization"],
      recommended_actions: [
        "Complete LeetCode Database 50 study plan",
        "Implement Postgres indexing and query profiling in a sample project",
        "Study relational normalization and ACID transactions",
      ],
    },
    {
      phase_number: 2,
      title: "Phase 2: DevOps & Containerization",
      estimated_weeks: 4,
      progress: 20,
      skills: ["Docker", "Docker Compose", "CI/CD Pipelines"],
      recommended_actions: [
        "Containerize a 3-tier microservice application",
        "Deploy containerized apps using GitHub Actions CI/CD to AWS ECS/EKS",
        "Learn container security and multi-stage builds",
      ],
    },
    {
      phase_number: 3,
      title: "Phase 3: System Design & Mock Placement Drills",
      estimated_weeks: 3,
      progress: 0,
      skills: ["System Design", "High-Level Architecture", "Mock Interviews"],
      recommended_actions: [
        "Design Rate Limiter, URL Shortener, and Chat Application architectures",
        "Participate in 3 peer-to-peer technical mock interview drills",
        "Refine HR behavioral questions using STAR method",
      ],
    },
  ],
};

export const MOCK_TPO_ANALYTICS_RESPONSE = {
  overall_readiness_percentage: 78.4,
  total_students: 450,
  ready_students_count: 245,
  near_ready_count: 135,
  vulnerable_count: 70,
  placement_trends: [
    { semester: "Sem 3", CSE: 55, ISE: 48, ECE: 40, Overall: 48 },
    { semester: "Sem 4", CSE: 68, ISE: 60, ECE: 52, Overall: 60 },
    { semester: "Sem 5", CSE: 75, ISE: 72, ECE: 64, Overall: 70 },
    { semester: "Sem 6", CSE: 84, ISE: 79, ECE: 70, Overall: 78 },
    { semester: "Sem 7", CSE: 88, ISE: 82, ECE: 74, Overall: 81 },
    { semester: "Sem 8", CSE: 91, ISE: 84, ECE: 76, Overall: 84 },
  ],
  departmental_readiness: [
    {
      department: "CSE",
      readiness_percentage: 91.0,
      total_students: 140,
      placed_or_ready: 127,
    },
    {
      department: "ISE",
      readiness_percentage: 84.0,
      total_students: 95,
      placed_or_ready: 80,
    },
    {
      department: "ECE",
      readiness_percentage: 76.0,
      total_students: 110,
      placed_or_ready: 84,
    },
    {
      department: "AIML",
      readiness_percentage: 76.0,
      total_students: 60,
      placed_or_ready: 46,
    },
    {
      department: "MECH",
      readiness_percentage: 52.0,
      total_students: 45,
      placed_or_ready: 23,
    },
  ],
  vulnerable_cohort: [
    {
      student_id: "STU1042",
      name: "Alex Johnson",
      department: "CSE",
      semester: 6,
      cgpa: 6.2,
      placement_probability: 48.5,
      readiness_status: "Needs Training",
      key_deficits: ["Backlogs (2)", "Low Aptitude (52%)", "No Internships"],
      recommended_bootcamp: "Core DSA & Aptitude Bootcamp",
    },
    {
      student_id: "STU1088",
      name: "Rohan Patel",
      department: "ECE",
      semester: 6,
      cgpa: 6.5,
      placement_probability: 54.0,
      readiness_status: "Needs Training",
      key_deficits: ["Missing Coding Practice", "No Cloud Skills"],
      recommended_bootcamp: "Python & Embedded Systems Prep",
    },
    {
      student_id: "STU1105",
      name: "Priya Sharma",
      department: "ISE",
      semester: 7,
      cgpa: 5.9,
      placement_probability: 42.0,
      readiness_status: "Needs Training",
      key_deficits: ["Low CGPA (<6.0)", "No Verified Certs", "Aptitude Deficit"],
      recommended_bootcamp: "Quantitative Mastery & Technical Interview Prep",
    },
    {
      student_id: "STU1132",
      name: "Kavya Murthy",
      department: "AIML",
      semester: 6,
      cgpa: 7.1,
      placement_probability: 58.0,
      readiness_status: "Needs Training",
      key_deficits: ["Low Soft Skills (2.4)", "Zero Projects"],
      recommended_bootcamp: "Communication Drills & End-to-End Projects",
    },
    {
      student_id: "STU1021",
      name: "Ananya Rao",
      department: "CSE",
      semester: 8,
      cgpa: 8.9,
      placement_probability: 92.5,
      readiness_status: "Ready",
      key_deficits: [],
      recommended_bootcamp: "Advanced FAANG Mock Interviews",
    },
    {
      student_id: "STU1055",
      name: "Vikram Seth",
      department: "ISE",
      semester: 8,
      cgpa: 7.8,
      placement_probability: 74.0,
      readiness_status: "Near-Ready",
      key_deficits: ["Missing Cloud Certs"],
      recommended_bootcamp: "AWS Certified Practitioner FastTrack",
    },
    {
      student_id: "STU1190",
      name: "Rahul Verma",
      department: "MECH",
      semester: 7,
      cgpa: 6.1,
      placement_probability: 50.0,
      readiness_status: "Needs Training",
      key_deficits: ["Zero Software Projects", "No Python/SQL"],
      recommended_bootcamp: "Full-Stack Foundation for Core Engineering",
    },
  ],
  skill_deficit_matrix: {
    skills: ["DSA", "Java", "SQL", "Python", "Cloud/DevOps", "System Design"],
    departments: [
      {
        department: "CSE",
        deficits: { DSA: 18, Java: 22, SQL: 12, Python: 14, "Cloud/DevOps": 48, "System Design": 52 },
      },
      {
        department: "ISE",
        deficits: { DSA: 24, Java: 30, SQL: 15, Python: 20, "Cloud/DevOps": 55, "System Design": 60 },
      },
      {
        department: "ECE",
        deficits: { DSA: 58, Java: 65, SQL: 45, Python: 32, "Cloud/DevOps": 78, "System Design": 82 },
      },
      {
        department: "AIML",
        deficits: { DSA: 35, Java: 50, SQL: 25, Python: 10, "Cloud/DevOps": 60, "System Design": 65 },
      },
      {
        department: "MECH",
        deficits: { DSA: 82, Java: 88, SQL: 70, Python: 45, "Cloud/DevOps": 90, "System Design": 94 },
      },
    ],
  },
};
